INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(555,	'Oglevie')
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(730,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1030,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1130,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1330,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1430,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1525,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1605,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1648,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1712,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1723,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1747,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1830,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(1930,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(2030,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(2130,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(2230,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(2330,	"Oglevie")
INSERT INTO WeekdaysFromTheCity (DepartureTime, TrainStop) VALUES(2430,	"Oglevie")



INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(539,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(604,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(631,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(706,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(724,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(754,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(828,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(854,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(954,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1054,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1154,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1304,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1454,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1554,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1630,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1709,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1754,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(1854,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(2054,	"Edison Park")	
INSERT INTO WeekdaysToTheCity (DepartureTime, TrainStop) VALUES(2154,	"Edison Park")

 
INSERT INTO WeatherPictures ( url) VALUES ("http://bitbyte.site/assets/images/sunny.gif")
INSERT INTO WeatherPictures ( url) VALUES ("https://i.gifer.com/ZIZ1.gif")
INSERT INTO WeatherPictures ( url) VALUES ("https://cdn.dribbble.com/users/910669/screenshots/2248501/moon2.gif")
INSERT INTO WeatherPictures ( url) VALUES ("https://cdn.dribbble.com/users/737003/screenshots/2032212/cloudtimelapse.gif")